GET http://localhost:8080/contacts
###
GET https://cse241-project.onrender.com/contacts


###
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
  "firstName": "Brandom",
  "lastName": "Rodriguez",
  "email": "Rodriguez@test.com",
  "favoriteColor": "Gray",
  "birthday": "2/9/92"
}
###
PUT http://localhost:8080/contacts/6510ed3dad653c8f24b1e114 HTTP/1.1 
content-type: application/json

{
"firstName":"Rose", 
"lastName":"Munes", 
"email":"Munes@gmail.com", 
"favoriteColor":"Red", 
"birthday":"11/09/95"
}
### 
DELETE http://localhost:8080/contacts/6510ed28ad653c8f24b1e112 HTTP/1.1