GET http://localhost:8080/contacts
###
GET https://cse241-project.onrender.com/contacts


###
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
  "firstName": "Ashley",
  "lastName": "Weaver",
  "email": "aWeaver@test.com",
  "favoriteColor": "Brown",
  "birthday": "06/19/2000"
}
###
PUT http://localhost:8080/contacts/65141257f05659189dfa3cbf HTTP/1.1 
content-type: application/json

{
"firstName":"Sarah", 
"lastName":"Birch", 
"email":"test@gmail.com", 
"favoriteColor":"Green", 
"birthday":"12/12/20"
}
### 
DELETE http://localhost:8080/contacts/65141257f05659189dfa3cbf HTTP/1.1